### ISSUE TITLE
timeout error

### ISSUE THREAD

**Issue by cmpscabral** [vesln/captureme#1]
Hi,
Just installed this and every time I run a command I get this error:

Test did not see a new command for 90 seconds. Timing out.
error

Is this normal? Also for the last job (if I request several different screen captures) the job doesn't terminate, I have to terminate it in SauceLabs control panel - I'm not sure how will this affect the minutes available on my account.

Thanks!

EDIT: the error is shown in SauceLabs control panel, not in the command line.

**Comment by vesln** [comment]
Hi Carlos,

Thanks for opening the issue! Investigating... will keep you posted.
